package dynamicc.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.editor.runtime.style.AbstractStyleClass;
import jetbrains.mps.editor.runtime.style.StyleAttributes;
import jetbrains.mps.openapi.editor.style.StyleRegistry;
import jetbrains.mps.nodeEditor.MPSColors;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Variable_StyleSheet {
  /**
   * 
   * @deprecated Since MPS 3.5 use generated StyleClass
   */
  @Deprecated
  public static void apply_VariableName(Style style, EditorCell editorCell) {
    SNode node = (editorCell == null ? null : editorCell.getSNode());
    EditorContext editorContext = (editorCell == null ? null : editorCell.getContext());
    new VariableNameStyleClass(editorContext, node).apply(style, editorCell);
  }

  public static class VariableNameStyleClass extends AbstractStyleClass {
    public VariableNameStyleClass(EditorContext editorContext, SNode node) {
      super(editorContext, node);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
      style.set(StyleAttributes.TEXT_COLOR, StyleRegistry.getInstance().getSimpleColor(MPSColors.magenta));
      style.set(StyleAttributes.UNDERLINED, _StyleParameter_QueryFunction_pptb9q_a1a());
    }

    private boolean _StyleParameter_QueryFunction_pptb9q_a1a() {
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(SNodeOperations.getConcept(getNode())), CONCEPTS.ValVariable$HQ)) {
        return false;
      }

      return true;
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ValVariable$HQ = MetaAdapterFactory.getConcept(0xa6d9727f49824bf8L, 0xabdd083fea5126abL, 0x3a6fd2de0c36cfdaL, "dynamicc.structure.ValVariable");
  }
}
